# Generated by Django 5.2.4 on 2025-07-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fact_up_blog", "0002_post_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
