# Generated by Django 5.2.4 on 2025-07-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fact_up_blog", "0003_post_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")], default=0
            ),
        ),
    ]
