# Generated by Django 5.2.4 on 2025-07-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fact_up_blog", "0005_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_on"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_on"]},
        ),
    ]
