# Generated by Django 5.2.4 on 2025-07-13 14:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fact_up_blog", "0006_alter_comment_options_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
